DEBUG_CAN = True
DEBUG_LIDAR = False
DEBUG_VIRTUAL = True
DEBUG_VCAN = False

CHANNEL = 'can0'
VCHANNEL = 'vcan0'
LIDAR_DEVICE = '/dev/ttyACM0'

CAN_IDS = {
    'ROBOT_POSITION': 0x3E3,
    'ROBOT_SPEED': 0x3E4,
    'OTHER_ROBOT_POSITION': 0x3E5,
    'ROBOT_STATUS': 0x402,
    'DISTANCE_SENSOR': 0x670,
    'MOTION_CMD': 0x7F0,
    'ST_CMD': 0x710,
    'OBST_MAP': 0x70F
}

MOTION_CMDS = {
    'STOP': 0x82,
    'BRAKE': 0x83,
    'SET_POSITION': 0x84,
    'FW_TO_DISTANCE': 0x85,
    'ROTATE_RELATIVE': 0x88,
    'SET_SPEED': 0x8C,
}
