DEBUG_CAN = True
DEBUG_VIRTUAL = True
CHANNEL = 'can0'

CAN_IDS = {
    'ROBOT_POSITION': 0x3E3,
    'ROBOT_SPEED': 0x3E4,
    'OTHER_ROBOT_POSITION': 0x3E5,
    'ROBOT_STATUS': 0x402,
    'DISTANCE_SENSOR': 0x670,
    'MOTION_CMD': 0x7F0,
    'ST_CMD': 0x710,
    'OBST_MAP': 0x70F
}
