DEBUG_CAN = True
CHANNEL = 'can0'

ID_ROBOT_POSITION       = 0x3E3
ID_ROBOT_SPEED          = 0x3E4
ID_OTHER_ROBOT_POSITION = 0x3E5
ID_ROBOT_STATUS         = 0x402
ID_DISTANCE_SENSOR      = 0x670
ID_DISTANCE_SENSOR      = 0x670
ID_MOTION_CMD           = 0x7F0
ID_ST_CMD               = 0x710
ID_OBST_MAP             = 0x70F
