# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Development

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "docs/**"
  push:
    branches-ignore: [upgrade]
    paths:
      - "!README.md"
      - "!.gitignore"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e "git+https://github.com/simondlevy/BreezyLidar.git#egg=BreezyLidar&subdirectory=python" # lidar library
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Test with pytest
        run: python3 main.py & (sleep 3; pytest .)
